const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const source = read('src/js/analysis/skin-analysis.js');
const storefrontSource = read('src/js/catalog/storefront.js');
const html = read('index.html');
const siteCss = read('src/styles/site.css');
const hero = read('src/components/home/HeroBanner.jsx');
const brandBar = read('src/components/home/BrandBar.jsx');
const categories = read('src/components/home/CategorySection.jsx');
const productList = read('src/components/home/ProductList.jsx');
const productCard = read('src/js/catalog/product-card.js');
const brandShowcase = read('src/components/home/BrandShowcase.jsx');
const header = read('src/components/layout/Header.jsx');
const help = read('src/components/home/HelpSection.jsx');
assert(!html.includes('cdn.tailwindcss.com'));
assert(siteCss.includes('@import "tailwindcss"'));
assert(siteCss.includes('--color-brand-primary'));
assert(hero.includes('className="leading-[1.05]"'));
assert(hero.includes('className="stage-podium"'));
assert(hero.includes('className="hero-carousel-controls"'));
assert(hero.includes('className="body-stage-podium"'));
assert(!hero.includes('data-feather="sparkles"'));
assert(!hero.includes('className="editorial-card editorial-card--body"'));
assert(hero.includes('className="hero-slide hero-slide--fragrance"'));
assert(hero.includes('data-carousel-dot="3"'));
assert(brandBar.includes('data-active-slide="0"'));
assert(brandBar.includes('data-active-slide="1"'));
assert(brandBar.includes('data-active-slide="2"'));
assert(brandBar.includes('data-active-slide="3"'));
assert(brandBar.includes('brand-tab-wordmark--ai">AI SKINID'));
assert(brandBar.includes(`brand-tab-wordmark--dvah">D'VAH`));
assert(siteCss.includes('.desktop-nav a.is-active'));
assert(siteCss.includes('.brand-tab.is-active::before'));
assert(storefrontSource.includes("brandTabs.forEach((tab) => tab.addEventListener('click'"));
assert(categories.includes('rilastil-acnestil-body-spray-150ml.avif'));
assert(!categories.includes("twon-body-lotion.png')} alt=\"\" /></span><span className=\"category-copy\"><small>06"));
assert(siteCss.includes('/* Balanced category grid: one premium visual system across all six cards. */'));
assert(siteCss.includes('grid-template-columns:repeat(3,minmax(0,1fr))'));
assert(productList.includes('id="brand-filter-select"'));
assert(productList.includes('id="step-filter-select"'));
assert(productList.includes('data-catalog-dropdown'));
assert(productList.includes('catalog-dropdown__panel'));
assert(productList.includes('id="benefit-filter-select"'));
assert(productList.includes('id="product-search" type="search"'));
assert(read('src/components/home/FeaturedProducts.jsx').includes('id="featured-products"'));
assert(header.includes('aria-controls="product-menu"'));
assert(header.includes('onMouseEnter={open}'));
assert(storefrontSource.includes("($('#featured-products') || $('#catalog'))?.scrollIntoView"));
assert(!storefrontSource.includes('setCatalogStepFilterVisibility'));
assert(!siteCss.includes('.catalog-filter-select.is-context-hidden'));
assert(siteCss.includes('/* Homepage visual rhythm and depth system. */'));
assert(siteCss.includes('--rhythm-anchor:#8b3a4a'));
assert(siteCss.includes('#categories .category-item'));
assert(siteCss.includes('.help-shop .concern-card'));
assert(siteCss.includes('.brand-card--rilastil .brand-card-media{background:radial-gradient'));
assert(siteCss.includes('.brand-card--rilastil .brand-card-media img{transform:scale(1.18)}'));
assert(siteCss.includes('.trust-strip{border-top:1px solid #eee6e8'));
assert(siteCss.includes('background:#fff;color:#302b2e'));
assert(help.includes('className="gentle-advisor-grid"') || help.includes('className="container gentle-advisor-grid"'));
assert(help.includes('openConsultation'));
assert(help.includes('tri-mun-kiem-dau'));
assert(fs.existsSync(path.join(root, 'src/assets/images/banners/ai-skin-model-v1.png')));
assert(siteCss.includes('linear-gradient(135deg,#1f070c 0%,#3d121b 56%,#6b2635 100%)'));
assert(siteCss.includes('linear-gradient(135deg,#fb7185 0%,#e11d48 100%)'));
assert(siteCss.includes('background:rgba(255,255,255,.07)'));
assert(siteCss.includes('border:1px solid rgba(255,255,255,.2)!important'));
assert(siteCss.includes('backdrop-filter:blur(16px) saturate(125%)'));
assert(siteCss.includes('color:rgba(255,255,255,.78)'));
assert(storefrontSource.includes("function syncPrimaryNavigation(step = 'all')"));
assert(storefrontSource.includes("link.classList.toggle('is-active', isActive)"));
assert(source.includes('window.syncPrimaryNavigation?.(step)'));
assert(!productList.includes('placeholder="Tìm sản phẩm, hoạt chất'));
assert(!productCard.includes('public${p.image}'));
assert(!productCard.includes('<span class="product-badge ${tierColor}">${p.tier}</span>'));
assert(productCard.includes('window.SKINID_ASSET_URL'));
assert(productCard.includes(".join(' · ')"));
assert(productCard.includes('class="product-card__cart-button" aria-label="Thêm'));
assert(productCard.includes('<span>Thêm vào giỏ</span>'));
assert(productCard.includes('product-card__benefit'));
assert(productCard.includes('product-card__social'));
assert(siteCss.includes('/* Flat editorial catalogue controls and product-card hierarchy. */'));
assert(siteCss.includes('border-bottom:1px solid #ebe5e7!important'));
assert(siteCss.includes('.catalog-dropdown__option.is-active'));
assert(siteCss.includes('.product-card__media img{transform:scale(1.12)}'));
assert(siteCss.includes('.product-card__footer{margin-top:auto'));
assert(brandShowcase.includes('twon-body-lotion-cutout.png'));
assert(brandShowcase.includes('dvah-kamal-cutout.png'));
assert(brandShowcase.includes('/images/brands/twon.png'));
assert(brandShowcase.includes('/images/brands/dvah.png'));
assert(!brandShowcase.includes('Xem 46 sản phẩm'));
assert.equal((brandShowcase.match(/Khám phá bộ sưu tập/g) || []).length, 3);
assert(read('src/pages/HomePage.jsx').includes('<ProductDetailModal />'));
assert(read('src/components/dialogs/ProductDetailModal.jsx').includes('id="product-detail-modal"'));
assert(read('src/components/analysis/SkincareRoutine.jsx').includes('id="privacy-modal"'));
assert(!read('src/components/analysis/SkincareRoutine.jsx').includes(String.raw`</div>\n`));
assert(source.includes('grid.appendChild(createProductCard(p))'));
assert(source.includes('container.appendChild(createProductCard(p))'));
assert(source.includes("variant: 'horizontal'"));
const shared = read('src/js/catalog/product-card.js');
assert(shared.includes('product-card__name'));
assert(shared.includes('product-card__selection'));
assert(shared.includes("checkbox.type = 'checkbox'"));
const checkbox = { checked: false };
const button = { disabled: true, classList: { add() {} } };
const context = {
  document: { getElementById: id => id === 'privacy-consent-checkbox' ? checkbox : button },
  window: { currentRoutineIds: ['a', 'b', 'a'], excludedRoutineIds: new Set(['b']), cartManager: true },
  cartManager: { addItem: (id, quantity) => added.push([id, quantity]) },
  showToast: message => messages.push(message)
};
const added = [], messages = [];
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('function togglePrivacyButton()'), source.indexOf('async function requestCameraPermissionAndProceed')), context);
context.togglePrivacyButton();
assert.equal(button.disabled, true);
checkbox.checked = true;
context.togglePrivacyButton();
assert.equal(button.disabled, false);
vm.runInContext(source.slice(source.lastIndexOf('function addAllToCart()'), source.indexOf('// BOOTSTRAP INITIALIZATION')), context);
context.addAllToCart();
assert.deepEqual(added, [['a', 1]]);
context.window.excludedRoutineIds.add('a');
context.addAllToCart();
assert.equal(added.length, 1);
assert(messages.at(-1).includes('ít nhất một'));
console.log('PASS: shared components, compiled Tailwind theme, consent states, selected routine cart items and empty selection.');
